export enum PopupToBackGroundMessageType {
    GET_ALL = 'GET_ALL',
    DELETE = 'DELETE',
    CLEAR = 'CLEAR',
    GREET = 'GREET',
    GET_ALL_COLLECTIONS = 'GET_ALL_COLLECTIONS',
    GET_COLLECTION = 'GET_COLLECTION',
    ADD_COLLECTION = 'ADD_COLLECTION',
    DELETE_COLLECTION = 'DELETE_COLLECTION',
    ADD_RECORD = 'ADD_RECORD',
    DELETE_RECORD = 'DELETE_RECORD',
    UPDATE_RECORD = 'UPDATE_RECORD',
}